apiVersion: apps/v1
kind: Deployment
metadata:
  name: dok-webhook
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    spec:
      imagePullSecrets:
        - name: dok-harbor-pull-secret
      containers:
        - name: dok-webhook
          image: dok-webhook-service-image
          env:
            - name: DATABASE__USER
              valueFrom:
                secretKeyRef:
                  name: dok-webhook-database-auth
                  key: POSTGRES_USER
            - name: DATABASE__PASS
              valueFrom:
                secretKeyRef:
                  name: dok-webhook-database-auth
                  key: POSTGRES_PASSWORD
            - name: DATABASE__HOST
              value: dok-webhook-database
          envFrom:
            - configMapRef:
                name: dok-webhook
            - secretRef:
                name: dok-webhook
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 250m
              memory: 1200Mi
            requests:
              cpu: 200m
              memory: 600Mi

