apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: ops-envconfig-overlay
  envs:
  - config.env
  options:
    labels:
      ops: replacement
    disableNameSuffixHash: true
