apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dok-webhook
spec:
  selector:
    matchLabels:
      app: dok-webhook
      app/component: webhook
  endpoints:
    - port: http
