apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.abraxas.ch/componet: service
    app.abraxas.ch/instance: APP_INSTANCE
    app.abraxas.ch/name: APP_NAME
    app.abraxas.ch/part-of: APP_PART_OF
    logformat: json

resources:
- deployment.yaml
- service-monitor.yaml
- service.yaml
