- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 250Mi
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 350Mi
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 120m
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 150m
