apiVersion: v1
kind: ConfigMap
metadata:
  name: APP_INSTANCE-pgpool-configmap
data:
  PGPOOL_PARAMS_BACKEND_HOSTNAME0: APP_INSTANCE-database
  PGPOOL_PARAMS_BACKEND_HOSTNAME1: APP_INSTANCE-database-repl
  PGPOOL_PARAMS_BACKEND_PORT0: "5432"
  PGPOOL_PARAMS_BACKEND_PORT1: "5432"
  PGPOOL_PARAMS_BACKEND_WEIGHT0: "1"
  PGPOOL_PARAMS_BACKEND_WEIGHT1: "1"
  PGPOOL_PARAMS_BACKEND_FLAG0: ALWAYS_PRIMARY|DISALLOW_TO_FAILOVER
  PGPOOL_PARAMS_BACKEND_FLAG1: DISALLOW_TO_FAILOVER
  PGPOOL_PARAMS_LISTEN_ADDRESSE: '*'
  PGPOOL_PARAMS_SR_CHECK_PERIOD: "0"
  PGPOOL_PARAMS_HEALTH_CHECK_PERIOD: "0"
  PGPOOL_PARAMS_FAILOVER_ON_BACKEND_ERROR: 'off'
  PGPOOL_ENABLE_POOL_PASSWD: 'off'
  PGPOOL_PASSWORD_ENCRYPTION_METHOD: md5
  PGPOOL_SKIP_PASSWORD_ENCRYPTION: 'true'
  PGPOOL_PARAMS_ENABLE_POOL_HBA: 'off'
  PGPOOL_PARAMS_SSL: 'on'
  PGPOOL_PARAMS_NUM_INIT_CHILDREN: "95"
  PGPOOL_PARAMS_MAX_POOL: "1"
  PGPOOL_PARAMS_LOG_MIN_MESSAGES: warning
  PGPOOL_PARAMS_ALLOW_CLEAR_TEXT_FRONTEND_AUTH: 'on'
