apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.abraxas.ch/component: pooler
    app.abraxas.ch/instance: APP_INSTANCE-pgpool
    app.abraxas.ch/name: APP_NAME
    app.abraxas.ch/part-of: APP_PART_OF
    logformat: pgpool

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
