apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.abraxas.ch/componet: database
    app.abraxas.ch/instance: APP_INSTANCE-database
    app.abraxas.ch/name: APP_NAME
    app.abraxas.ch/part-of: APP_PART_OF
    logformat: default

resources:
- postgres.yaml
- podmonitor.yaml
