apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: APP_INSTANCE-database
  labels:
    team: dok
spec:
  teamId: "dok"
  volume:
    size: 5Gi
    storageClass: data-hot
  numberOfInstances: 1 #reoplicas
  users:
    dbadmin:  # database owner. Predefined roles: superuser, inherit, login, nologin, createrole, createdb, replication, bypassrls
      - superuser
      - createdb
    grafanareadonly: [LOGIN, NOSUPERUSER, NOINHERIT, NOCREATEDB, NOCREATEROLE]
  databases:
    postgres: dbadmin
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  postgresql:
    version: "14"
    parameters:  # Expert section, Overwrite default values of postgresql.conf
      max_connections: "99"
      timezone: "Europe/Zurich"
  #run postgresql container as postgresql user instead of root
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  #sidecar containers used for exporting PostgreSQL server metrics
  sidecars:
  - env:
    - name: DATA_SOURCE_URI
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: DATA_SOURCE_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: dbadmin.APP_INSTANCE-database.credentials.postgresql.acid.zalan.do
    - name: DATA_SOURCE_PASS
      valueFrom:
        secretKeyRef:
          key: password
          name: dbadmin.APP_INSTANCE-database.credentials.postgresql.acid.zalan.do
    - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
      value: "true"
    image: quay.io/prometheuscommunity/postgres-exporter:v0.11.0
    name: exporter
    ports:
    - containerPort: 9187
      name: exporter
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
